### ISSUE TITLE
Enabling debug output causes a panic.

### ISSUE THREAD

**Issue by TsarFox** [mattnenterprise/rust-imap#68]
Running the following code with version 0.7.0 of the library:

```
fn main() {
    let domain = "imap.gmail.com";
    let port = 993;
    let socket_addr = (domain, port);
    let ssl_connector = TlsConnector::builder().unwrap().build().unwrap();
    let mut imap_socket = Client::secure_connect(socket_addr, domain, ssl_connector).unwrap();

    imap_socket.debug = true;

    imap_socket.login("username", "password").unwrap();

    imap_socket.logout().unwrap();
}
```

Has a panic at runtime with the following stacktrace:

```
[jakob@Epsilon comptest]$ RUST_BACKTRACE=1 target/debug/comptest 
C: a1 LOGIN "username" "password"
thread 'main' panicked at 'attempt to subtract with overflow', /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:574:30
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <imap::client::Client<T>>::readline
             at /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:574
  11: <imap::client::Client<T>>::read_response_onto
             at /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:496
  12: <imap::client::Client<T>>::read_response
             at /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:482
  13: <imap::client::Client<T>>::run_command_and_read_response
             at /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:477
  14: <imap::client::Client<T>>::run_command_and_check_ok
             at /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:466
  15: <imap::client::Client<T>>::login
             at /home/jakob/.cargo/registry/src/github.com-1ecc6299db9ec823/imap-0.7.0/src/client.rs:291
  16: comptest::main
             at src/main.rs:19
  17: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  21: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  22: main
  23: __libc_start_main
  24: _start
```

**Comment by jonhoo** [comment]
Thanks! This should be fixed after #65 landed, but we haven't pushed a new version yet. And unfortunately that's not something I have the power to do :) cc @mattnenterprise.

**Comment by mattnenterprise** [comment]
@jonhoo I just pushed out a new version with that fix.

**Comment by jonhoo** [comment]
Fixed!
